"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import logging
import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# =============================================================================
# SECRETS MANAGEMENT
# =============================================================================
# Support for multiple secret management providers:
# - AWS Secrets Manager
# - Google Cloud Secret Manager
# - Azure Key Vault
# - HashiCorp Vault
# - Environment Variables (fallback)

try:
    from config.secrets import get_secret

    # Try to get SECRET_KEY from secrets manager first
    SECRETS_PROVIDER = os.environ.get("SECRETS_PROVIDER", "env").lower()
    if SECRETS_PROVIDER != "env":
        # Try to get from secrets manager
        django_secret = get_secret("DJANGO_SECRET_KEY")
        if django_secret:
            SECRET_KEY = django_secret
        else:
            # Fallback to environment variable
            SECRET_KEY = os.environ.get(
                "DJANGO_SECRET_KEY",
                "django-insecure-h$tolzfl80*2w(!b8na@@uz-5b&z_+z1ra2gj*m(v)3)e9ebji",
            )
    else:
        # Use environment variables directly
        SECRET_KEY = os.environ.get(
            "DJANGO_SECRET_KEY", "django-insecure-h$tolzfl80*2w(!b8na@@uz-5b&z_+z1ra2gj*m(v)3)e9ebji"
        )
except ImportError:
    # Secrets module not available, use environment variables
    SECRET_KEY = os.environ.get(
        "DJANGO_SECRET_KEY", "django-insecure-h$tolzfl80*2w(!b8na@@uz-5b&z_+z1ra2gj*m(v)3)e9ebji"
    )


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")


# Application definition

INSTALLED_APPS = [
    # Jazzmin must be before django.contrib.admin
    "jazzmin",
    # Django core apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",  # Required for allauth
    # Third-party apps
    "corsheaders",  # CORS support
    "rest_framework",
    "rest_framework_simplejwt",
    "drf_spectacular",  # OpenAPI schema generation
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    # Social providers (add as needed)
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.github",
    "allauth.socialaccount.providers.microsoft",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # CORS middleware (should be early)
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Allauth middleware (required)
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "config.urls"

# Site ID for django.contrib.sites (required for allauth)
SITE_ID = int(os.environ.get("SITE_ID", "1"))

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration with connection pooling support
DB_ENGINE = os.environ.get("DB_ENGINE", "django.db.backends.sqlite3")

if DB_ENGINE == "django.db.backends.postgresql":
    # PostgreSQL with connection pooling
    USE_DB_POOL = os.environ.get("USE_DB_POOL", "False") == "True"

    if USE_DB_POOL:
        try:
            # Import to verify availability (noqa: F401 - used for availability check)
            from django_db_connection_pool import backends  # noqa: F401

            DATABASES = {
                "default": {
                    "ENGINE": "django_db_connection_pool.backends.postgresql",
                    "NAME": os.environ.get("DB_NAME", ""),
                    "USER": os.environ.get("DB_USER", ""),
                    "PASSWORD": os.environ.get("DB_PASSWORD", ""),
                    "HOST": os.environ.get("DB_HOST", "localhost"),
                    "PORT": os.environ.get("DB_PORT", "5432"),
                    "OPTIONS": {
                        "MAX_CONNS": int(os.environ.get("DB_POOL_MAX_CONNS", "20")),
                        "MIN_CONNS": int(os.environ.get("DB_POOL_MIN_CONNS", "5")),
                    },
                }
            }
        except ImportError:
            # Fallback to standard PostgreSQL if pool not installed
            DATABASES = {
                "default": {
                    "ENGINE": "django.db.backends.postgresql",
                    "NAME": os.environ.get("DB_NAME", ""),
                    "USER": os.environ.get("DB_USER", ""),
                    "PASSWORD": os.environ.get("DB_PASSWORD", ""),
                    "HOST": os.environ.get("DB_HOST", "localhost"),
                    "PORT": os.environ.get("DB_PORT", "5432"),
                }
            }
    else:
        # Standard PostgreSQL without pooling
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": os.environ.get("DB_NAME", ""),
                "USER": os.environ.get("DB_USER", ""),
                "PASSWORD": os.environ.get("DB_PASSWORD", ""),
                "HOST": os.environ.get("DB_HOST", "localhost"),
                "PORT": os.environ.get("DB_PORT", "5432"),
            }
        }
elif DB_ENGINE == "django.db.backends.mysql":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.environ.get("DB_NAME", ""),
            "USER": os.environ.get("DB_USER", ""),
            "PASSWORD": os.environ.get("DB_PASSWORD", ""),
            "HOST": os.environ.get("DB_HOST", "localhost"),
            "PORT": os.environ.get("DB_PORT", "3306"),
            "OPTIONS": {
                "charset": "utf8mb4",
            },
        }
    }
else:
    # SQLite (default)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = os.environ.get("DJANGO_LANGUAGE_CODE", "pt-br")

TIME_ZONE = os.environ.get("DJANGO_TIME_ZONE", "America/Sao_Paulo")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = os.environ.get("STATIC_URL", "static/")
STATIC_ROOT = BASE_DIR / os.environ.get("STATIC_ROOT", "staticfiles")

# Media files (User uploaded files)
# https://docs.djangoproject.com/en/5.2/topics/files/

MEDIA_URL = os.environ.get("MEDIA_URL", "/media/")
MEDIA_ROOT = BASE_DIR / os.environ.get("MEDIA_ROOT", "media")

# =============================================================================
# CLOUD STORAGE CONFIGURATION
# =============================================================================
# Supports: AWS S3, Google Cloud Storage, Azure Blob Storage, DigitalOcean Spaces,
# Scaleway, MinIO, and other S3-compatible services

STORAGE_BACKEND = os.environ.get("STORAGE_BACKEND", "local").lower()

if STORAGE_BACKEND == "s3":
    # AWS S3 or S3-compatible (DigitalOcean Spaces, Scaleway, MinIO, etc.)
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "bucket_name": os.environ.get("AWS_STORAGE_BUCKET_NAME", ""),
                "access_key": os.environ.get("AWS_ACCESS_KEY_ID", ""),
                "secret_key": os.environ.get("AWS_SECRET_ACCESS_KEY", ""),
                "region_name": os.environ.get("AWS_S3_REGION_NAME", "us-east-1"),
                "endpoint_url": os.environ.get("AWS_S3_ENDPOINT_URL", None),  # For S3-compatible
                "custom_domain": os.environ.get("AWS_S3_CUSTOM_DOMAIN", None),
                "location": os.environ.get("AWS_S3_LOCATION", ""),
                "file_overwrite": os.environ.get("AWS_S3_FILE_OVERWRITE", "True") == "True",
                "default_acl": os.environ.get("AWS_DEFAULT_ACL", None),
                "querystring_auth": os.environ.get("AWS_QUERYSTRING_AUTH", "True") == "True",
                "querystring_expire": int(os.environ.get("AWS_QUERYSTRING_EXPIRE", "3600")),
            },
        },
        "staticfiles": {
            "BACKEND": "storages.backends.s3.S3StaticStorage",
            "OPTIONS": {
                "bucket_name": os.environ.get(
                    "AWS_STATIC_BUCKET_NAME", os.environ.get("AWS_STORAGE_BUCKET_NAME", "")
                ),
                "access_key": os.environ.get("AWS_ACCESS_KEY_ID", ""),
                "secret_key": os.environ.get("AWS_SECRET_ACCESS_KEY", ""),
                "region_name": os.environ.get("AWS_S3_REGION_NAME", "us-east-1"),
                "endpoint_url": os.environ.get("AWS_S3_ENDPOINT_URL", None),
                "custom_domain": os.environ.get(
                    "AWS_S3_STATIC_CUSTOM_DOMAIN", os.environ.get("AWS_S3_CUSTOM_DOMAIN", None)
                ),
                "location": os.environ.get("AWS_S3_STATIC_LOCATION", "static"),
            },
        },
    }
    # Set media URL from S3
    if os.environ.get("AWS_S3_CUSTOM_DOMAIN"):
        MEDIA_URL = f"https://{os.environ.get('AWS_S3_CUSTOM_DOMAIN')}/{os.environ.get('AWS_S3_LOCATION', '')}"
    else:
        bucket_name = os.environ.get("AWS_STORAGE_BUCKET_NAME", "")
        region = os.environ.get("AWS_S3_REGION_NAME", "us-east-1")
        endpoint = os.environ.get("AWS_S3_ENDPOINT_URL", f"https://s3.{region}.amazonaws.com")
        MEDIA_URL = f"{endpoint}/{bucket_name}/{os.environ.get('AWS_S3_LOCATION', '')}"

elif STORAGE_BACKEND == "gcs":
    # Google Cloud Storage
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
            "OPTIONS": {
                "bucket_name": os.environ.get("GS_BUCKET_NAME", ""),
                "project_id": os.environ.get("GS_PROJECT_ID", ""),
                "credentials": os.environ.get("GS_CREDENTIALS", None),  # Path to JSON credentials
                "location": os.environ.get("GS_LOCATION", ""),
                "file_overwrite": os.environ.get("GS_FILE_OVERWRITE", "True") == "True",
                "default_acl": os.environ.get("GS_DEFAULT_ACL", None),
                "querystring_auth": os.environ.get("GS_QUERYSTRING_AUTH", "True") == "True",
                "expiration": int(os.environ.get("GS_EXPIRATION", "86400")),
            },
        },
        "staticfiles": {
            "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
            "OPTIONS": {
                "bucket_name": os.environ.get(
                    "GS_STATIC_BUCKET_NAME", os.environ.get("GS_BUCKET_NAME", "")
                ),
                "project_id": os.environ.get("GS_PROJECT_ID", ""),
                "credentials": os.environ.get("GS_CREDENTIALS", None),
                "location": os.environ.get("GS_STATIC_LOCATION", "static"),
            },
        },
    }
    # Set media URL from GCS
    bucket_name = os.environ.get("GS_BUCKET_NAME", "")
    location = os.environ.get("GS_LOCATION", "")
    MEDIA_URL = f"https://storage.googleapis.com/{bucket_name}/{location}"

elif STORAGE_BACKEND == "azure":
    # Azure Blob Storage
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.azure_storage.AzureStorage",
            "OPTIONS": {
                "account_name": os.environ.get("AZURE_ACCOUNT_NAME", ""),
                "account_key": os.environ.get("AZURE_ACCOUNT_KEY", ""),
                "azure_container": os.environ.get("AZURE_CONTAINER", ""),
                "connection_string": os.environ.get("AZURE_CONNECTION_STRING", None),
                "location": os.environ.get("AZURE_LOCATION", ""),
                "expiration_secs": int(os.environ.get("AZURE_URL_EXPIRATION_SECS", "3600")),
                "overwrite_files": os.environ.get("AZURE_OVERWRITE_FILES", "True") == "True",
                "custom_domain": os.environ.get("AZURE_CUSTOM_DOMAIN", None),
            },
        },
        "staticfiles": {
            "BACKEND": "storages.backends.azure_storage.AzureStorage",
            "OPTIONS": {
                "account_name": os.environ.get("AZURE_ACCOUNT_NAME", ""),
                "account_key": os.environ.get("AZURE_ACCOUNT_KEY", ""),
                "azure_container": os.environ.get(
                    "AZURE_STATIC_CONTAINER", os.environ.get("AZURE_CONTAINER", "")
                ),
                "connection_string": os.environ.get("AZURE_CONNECTION_STRING", None),
                "location": os.environ.get("AZURE_STATIC_LOCATION", "static"),
            },
        },
    }
    # Set media URL from Azure
    account_name = os.environ.get("AZURE_ACCOUNT_NAME", "")
    container = os.environ.get("AZURE_CONTAINER", "")
    custom_domain = os.environ.get("AZURE_CUSTOM_DOMAIN")
    if custom_domain:
        MEDIA_URL = f"https://{custom_domain}/{container}/"
    else:
        MEDIA_URL = f"https://{account_name}.blob.core.windows.net/{container}/"

else:
    # Local storage (default)
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# =============================================================================
# JAZZMIN CONFIGURATION
# =============================================================================

JAZZMIN_SETTINGS = {
    "site_title": "Django Template Admin",
    "site_header": "Django Template",
    "site_brand": "Django Template",
    "site_logo": None,
    "login_logo": None,
    "login_logo_dark": None,
    "site_logo_classes": "img-circle",
    "site_icon": None,
    "welcome_sign": "Bem-vindo ao Django Template Admin",
    "copyright": "Django Template",
    "search_model": ["auth.User", "auth.Group"],
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "API Docs", "url": "/api/docs/", "new_window": True},
    ],
    "usermenu_links": [
        {"name": "API Docs", "url": "/api/docs/", "new_window": True},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["auth", "account", "socialaccount"],
    "custom_links": {
        "books": [
            {
                "name": "Make Messages",
                "url": "make_messages",
                "icon": "fas fa-comments",
                "permissions": ["books.view_book"],
            }
        ]
    },
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "account.EmailAddress": "fas fa-envelope",
        "socialaccount.SocialAccount": "fas fa-share-alt",
        "socialaccount.SocialToken": "fas fa-key",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": False,
    "custom_css": None,
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}

# =============================================================================
# DJANGO REST FRAMEWORK CONFIGURATION
# =============================================================================

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_FILTER_BACKENDS": [
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
}

# =============================================================================
# SIMPLE JWT CONFIGURATION
# =============================================================================

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=int(os.environ.get("JWT_ACCESS_TOKEN_LIFETIME_MINUTES", "60"))
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=int(os.environ.get("JWT_REFRESH_TOKEN_LIFETIME_DAYS", "7"))
    ),
    "ROTATE_REFRESH_TOKENS": os.environ.get("JWT_ROTATE_REFRESH_TOKENS", "True") == "True",
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
}

# =============================================================================
# DJANGO-ALLAUTH CONFIGURATION (SSO)
# =============================================================================

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",
    # `allauth` specific authentication methods, such as login by email
    "allauth.account.auth_backends.AuthenticationBackend",
]

# Allauth settings (using new API)
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = os.environ.get("ACCOUNT_EMAIL_VERIFICATION", "optional")
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_ADAPTER = "allauth.account.adapter.DefaultAccountAdapter"
ACCOUNT_FORMS = {}

# Social account settings
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_EMAIL_VERIFICATION = "optional"
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_ADAPTER = "allauth.socialaccount.adapter.DefaultSocialAccountAdapter"
SOCIALACCOUNT_FORMS = {}

# Social account providers configuration
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
        "APP": {
            "client_id": os.environ.get("GOOGLE_CLIENT_ID", ""),
            "secret": os.environ.get("GOOGLE_CLIENT_SECRET", ""),
            "key": "",
        },
    },
    "github": {
        "SCOPE": [
            "user",
            "user:email",
        ],
        "APP": {
            "client_id": os.environ.get("GITHUB_CLIENT_ID", ""),
            "secret": os.environ.get("GITHUB_CLIENT_SECRET", ""),
            "key": "",
        },
    },
    "microsoft": {
        "TENANT": os.environ.get("MICROSOFT_TENANT", "common"),
        "APP": {
            "client_id": os.environ.get("MICROSOFT_CLIENT_ID", ""),
            "secret": os.environ.get("MICROSOFT_CLIENT_SECRET", ""),
            "key": "",
        },
    },
}

# Login/Logout URLs
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"
ACCOUNT_LOGOUT_ON_GET = True

# =============================================================================
# CORS CONFIGURATION
# =============================================================================

CORS_ALLOWED_ORIGINS = os.environ.get(
    "CORS_ALLOWED_ORIGINS", "http://localhost:3000,http://localhost:8080"
).split(",")

CORS_ALLOW_CREDENTIALS = os.environ.get("CORS_ALLOW_CREDENTIALS", "True") == "True"

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# For development only - remove in production
CORS_ALLOW_ALL_ORIGINS = os.environ.get("CORS_ALLOW_ALL_ORIGINS", "False") == "True"

# CSRF trusted origins (should match CORS origins for POST requests)
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS.copy()

# =============================================================================
# SECURITY HEADERS
# =============================================================================

if not DEBUG:
    # Security settings for production
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = os.environ.get("SECURE_SSL_REDIRECT", "True") == "True"
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "filters": {
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "handlers": {
        "console": {
            "level": os.environ.get("LOG_LEVEL", "INFO"),
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs" / "django.log",
            "maxBytes": 1024 * 1024 * 10,  # 10 MB
            "backupCount": 5,
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": os.environ.get("LOG_LEVEL", "INFO"),
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": os.environ.get("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console", "file"],
            "level": "ERROR",
            "propagate": False,
        },
        "config": {
            "handlers": ["console", "file"],
            "level": os.environ.get("LOG_LEVEL", "INFO"),
            "propagate": False,
        },
    },
}

# Create logs directory if it doesn't exist
(BASE_DIR / "logs").mkdir(exist_ok=True)

# =============================================================================
# EMAIL CONFIGURATION
# =============================================================================

EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")

if EMAIL_BACKEND == "django.core.mail.backends.smtp.EmailBackend":
    EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com")
    EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
    EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True") == "True"
    EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL", "False") == "True"
    EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
    DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)

# =============================================================================
# CACHING CONFIGURATION (Optional)
# =============================================================================

CACHE_BACKEND = os.environ.get("CACHE_BACKEND", "dummy").lower()

if CACHE_BACKEND == "redis":
    try:
        import django_redis  # noqa: F401

        CACHES = {
            "default": {
                "BACKEND": "django.core.cache.backends.redis.RedisCache",
                "LOCATION": os.environ.get("CACHE_URL", "redis://127.0.0.1:6379/1"),
                "OPTIONS": {
                    "CLIENT_CLASS": "django_redis.client.DefaultClient",
                },
                "KEY_PREFIX": "django_template",
                "TIMEOUT": 300,
            }
        }
        # Use Redis for session storage
        SESSION_ENGINE = "django.contrib.sessions.backends.cache"
        SESSION_CACHE_ALIAS = "default"
    except ImportError:
        # Fallback to dummy cache if django-redis not installed
        CACHES = {
            "default": {
                "BACKEND": "django.core.cache.backends.dummy.DummyCache",
            }
        }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.dummy.DummyCache",
        }
    }

# =============================================================================
# DRF SPECTACULAR CONFIGURATION (OpenAPI/Swagger)
# =============================================================================

SPECTACULAR_SETTINGS = {
    "TITLE": os.environ.get("API_TITLE", "Django Template API"),
    "DESCRIPTION": os.environ.get(
        "API_DESCRIPTION", "A modern Django REST API template with SSO authentication"
    ),
    "VERSION": os.environ.get("API_VERSION", "1.0.0"),
    "SERVE_INCLUDE_SCHEMA": True,
    "SERVE_PERMISSIONS": ["rest_framework.permissions.AllowAny"],
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": "/api/v1/",
    "TAGS": [
        {"name": "Authentication", "description": "JWT and SSO authentication endpoints"},
        {"name": "Users", "description": "User management endpoints"},
        {"name": "Health", "description": "Health check endpoints"},
    ],
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "displayOperationId": False,
        "defaultModelsExpandDepth": 1,
        "defaultModelExpandDepth": 1,
        "displayRequestDuration": True,
        "filter": True,
        "showExtensions": True,
        "showCommonExtensions": True,
    },
    "REDOC_SETTINGS": {
        "expandSingleSchemaField": True,
        "hideDownloadButton": False,
    },
}

# =============================================================================
# RATE LIMITING CONFIGURATION
# =============================================================================

# Rate limiting using DRF's built-in throttling
REST_FRAMEWORK_THROTTLE_RATES = {
    "anon": os.environ.get("RATE_LIMIT_ANON", "100/hour"),  # Anonymous users
    "user": os.environ.get("RATE_LIMIT_USER", "1000/hour"),  # Authenticated users
    "burst": os.environ.get("RATE_LIMIT_BURST", "10/minute"),  # Burst limit
}

# Update REST_FRAMEWORK to use drf-spectacular
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_FILTER_BACKENDS": [
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",  # OpenAPI schema
    "EXCEPTION_HANDLER": "config.exceptions.custom_exception_handler",  # Custom error handler
    # Rate limiting
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",  # For anonymous users
        "rest_framework.throttling.UserRateThrottle",  # For authenticated users
    ],
    "DEFAULT_THROTTLE_RATES": REST_FRAMEWORK_THROTTLE_RATES,
}

# =============================================================================
# API VERSIONING CONFIGURATION
# =============================================================================

# API versioning support
# Use URL path versioning: /api/v1/, /api/v2/, etc.
# Versioning is handled via URL patterns in urls.py
# To add new versions, create config/api_v2.py and add path("api/v2/", include("config.api_v2"))
REST_FRAMEWORK["ALLOWED_VERSIONS"] = ["v1", "v2"]  # Add more versions as needed
REST_FRAMEWORK["DEFAULT_VERSION"] = "v1"

# =============================================================================
# SENTRY MONITORING (Optional)
# =============================================================================

SENTRY_DSN = os.environ.get("SENTRY_DSN", None)

if SENTRY_DSN:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration
        from sentry_sdk.integrations.logging import LoggingIntegration

        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[
                DjangoIntegration(
                    transaction_style="url",
                    middleware_spans=True,
                    signals_spans=True,
                    cache_spans=True,
                ),
                LoggingIntegration(
                    level=logging.INFO,  # Capture info and above as breadcrumbs
                    event_level=logging.ERROR,  # Send errors as events
                ),
            ],
            # Set traces_sample_rate to 1.0 to capture 100%
            # of transactions for performance monitoring.
            traces_sample_rate=float(os.environ.get("SENTRY_TRACES_SAMPLE_RATE", "0.1")),
            # Set profiles_sample_rate to 1.0 to profile 100%
            # of sampled transactions.
            profiles_sample_rate=float(os.environ.get("SENTRY_PROFILES_SAMPLE_RATE", "0.1")),
            # If you wish to associate users to errors (assuming you are using
            # django.contrib.auth) you may enable sending PII data.
            send_default_pii=os.environ.get("SENTRY_SEND_DEFAULT_PII", "False") == "True",
            # Environment
            environment=os.environ.get("SENTRY_ENVIRONMENT", "production" if not DEBUG else "development"),
            # Release version
            release=os.environ.get("SENTRY_RELEASE", None),
            # Before send callback
            before_send=lambda event, hint: event if not DEBUG else None,  # Don't send in debug mode
        )
    except ImportError:
        # Sentry SDK not installed, skip initialization
        pass
